services:
  - type: web
    name: proyecto-final-ml
    env: python
    plan: starter
    buildCommand: ./render-build.sh
    startCommand: gunicorn app:app
    envVars:
      PYTHON_VERSION: 3.10.12
