services:
  - type: web
    name: proyecto-final-ml
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      PYTHON_VERSION: 3.10.12
